global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'avalanchego'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9650']
    metrics_path: '/ext/metrics'
    scheme: 'http'
